Blogapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.homeview,name="home"),
    path('signup',views.signupview,name="signup"),
    path('login',views.loginview,name="login"),
    path('logout',views.logoutview,name="logout"),
    path('add_blog',views.add_blogview,name="add_blog"),
    path('save_blog',views.save_postview,name="save_blog"),
    path('show_post',views.show_postview,name="show_post"),
    path('posts/<slug:posturl>',views.post_detailview,name='post_detail'),
    path('edit/<slug:posturl>',views.edit_postview,name='edit_post'),
    path('update/<slug:posturl>',views.update_postview,name='update_post'),
    path('delete/<slug:posturl>',views.delete_view,name='delete_post'),
    path('category/<type>',views.category_view,name='category'),
    path('about',views.aboutview,name="about")
]

GrowthBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import Blogapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',include('Blogapp.urls'))
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Blogapp/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
import datetime
from django.utils import timezone
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from .util import *
from django.utils import timezone



class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Category(models.Model):
    category=models.CharField(max_length=100,default="")

    def __str__(self):
        return self.category


class Post(models.Model):
    user= models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    slug = models.SlugField(max_length = 250, null = True, blank = True)
    heading=models.TextField(max_length=500)
    body=RichTextUploadingField(blank=True,null=True)
    category=models.ForeignKey(Category,on_delete=models.PROTECT,null= True)
    likes= models.IntegerField(default=0)
    dislikes= models.IntegerField(default=0)
    creation_date=models.DateTimeField(default=timezone.now)
    thumb_url=models.CharField(max_length=200,default="{% static 'images/blogimage.jpg' %}")


@receiver(pre_save, sender=Post)
def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
	    instance.slug = unique_slug_generator(instance)




	# id->primary key
	# user ->foriegn key user
	# category ->many to many field category
	# heading
	# body
	# date created->creation date
	# likes
	# dislikes

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>About Us</title>
  <link rel="icon" href="{% static 'images/logo.ico'%}" type="image/x-icon">
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" />
  <meta name="_token" content="{{csrf_token}}">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
  <link href="{% static 'css/aos.css' %}" rel="stylesheet" />
  <link href="{% static 'css/ionicons.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/flaticon.css' %}" rel="stylesheet" />
  <link href="{% static 'css/icomoon.css' %}" rel="stylesheet" />
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/loader.css' %}">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />


</head>

<body>
{% include "navbar.html" %}
{% include "modal.html" %}

  





  <div class="hero-wrap js-fullheight" data-stellar-background-ratio="0.5"
    style="background-image: url({% static 'images/backgroundimage.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
        data-scrollax-parent="true">
        <div class="col-md-12 ftco-animate">
          <h1>About Us</h1>
        </div>
      </div>
    </div>
  </div>


  <section class="ftco-section bg-darkblack">

    <div class="container">
      <div class="container text-center">
        <h3 class="text-uppercase text-white">
          Our Team
        </h3>


        <div class="row mt-5">

          <div class="col-md-6">
            <div class="container text-center">
              <div class="card bg-lightblack mt-3 mx-auto" style="width: 18rem;">
                <img class="card-img-top" src="{% static 'images/suraj_photo.jpeg'%}" alt="Card image cap">
                <div class="card-body">
                  <div class="card-text">
                    <h3 style="color:white">
                      Suraj Songara
                    </h3>
                    <h5 style="color:rgb(116, 214, 18)">(Backend Developer)</h5>

                    <p>
                      <a href="https://github.com/SurajSongara"><i class="fab fa-github fa-2x mr-2"></i> </a>  
                      <a href="https://www.linkedin.com/in/surajsongara/"><i class="fab fa-linkedin-in fa-2x mr-2"></i></a>
                      <a href="mailto:suraj.songara@cdgi.edu.in"><i class="fab fa-google-plus-g fa-2x mr-2"></i></a>       
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-6">
            <div class="container text-center">
              <div class="card bg-lightblack mt-3 mx-auto" style="width: 18rem;">
                <img class="card-img-top" src="{% static 'images/vaibhav_photo.jpeg'%}" alt="Card image cap">
                <div class="card-body">
                  <div class="card-text">
                    <h3 style="color:white">
                      Vaibhav Savner
                    </h3>
                    <h5 style="color:rgb(116, 214, 18)">(Frontend Developer)</h5>
                    <p>
                      <a href="https://github.com/savnerji"><i class="fab fa-github fa-2x mr-2"></i> </a>  
                      <a href="https://www.linkedin.com/in/vaibhav-savner-17124b195"><i class="fab fa-linkedin-in fa-2x mr-2"></i></a>
                      <a href="mailto:vaibhavsavner05@gmail.com"><i class="fab fa-google-plus-g fa-2x mr-2"></i></a>               
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

  </section>




  {% include "footer.html" %}
</body>

</html>

templates/add_blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Add Blog</title>
    <link rel="icon" href="{% static 'images/logo.ico'%}" type="image/x-icon">
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" />
    <meta name="_token" content="{{csrf_token}}">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
    <link href="{% static 'css/aos.css' %}" rel="stylesheet" />
    <link href="{% static 'css/ionicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet" />
    <link href="{% static 'css/icomoon.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/loader.css' %}">
    <style>
        #id_heading {
            width: 100% !important;
            height: 50px !important;
        }

        @media screen and (max-device-width: 480px) and (orientation: portrait) {
            #cke_id_body {
                position: relative !important;
                width: fit-content !important;
            }
        }

        @media screen and (max-device-width: 640px) and (orientation: landscape) {
            #cke_id_body {
                position: relative !important;
                width: fit-content !important;
            }
        }
    </style>
</head>
<body>
{% include "navbar.html" %}
{% include "modal.html" %}

    <div class="hero-wrap js-fullheight" data-stellar-background-ratio="0.5"
        style="background-image: url({% static 'images/backgroundimage.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
                data-scrollax-parent="true">
                <div class="col-md-12 ftco-animate">
                    <h1>Add Blog</h1>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid bg-darkblack d-flex justify-content-center">
        <div class="text mt-4">
            <form method="POST" class="mt-5" action="{% url 'save_blog' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="img-fluid">
                    {{form.media}}
                </div>
                <div class="container text-center">
                    <button class="links mt-1 mb-4 " type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>

{% include "footer.html" %}
</body>
</html>

templates/edit_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Edit blog</title>
  <link rel="icon" href="{% static 'images/logo.ico'%}" type="image/x-icon">
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" />
  <meta name="_token" content="{{csrf_token}}">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
  <link href="{% static 'css/aos.css' %}" rel="stylesheet" />
  <link href="{% static 'css/ionicons.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/flaticon.css' %}" rel="stylesheet" />
  <link href="{% static 'css/icomoon.css' %}" rel="stylesheet" />
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/loader.css' %}">

  <style>
    #id_heading {
      width: 100% !important;
      height: 50px !important;
    }

    @media screen and (max-device-width: 480px) and (orientation: portrait) {
      #cke_id_body {
        position: relative !important;
        width: fit-content !important;
      }
    }

    @media screen and (max-device-width: 640px) and (orientation: landscape) {
      #cke_id_body {
        position: relative !important;
        width: fit-content !important;
      }
    }
  </style>

</head>

<body>


{% include "navbar.html" %}
{% include "modal.html" %}






  <div class="hero-wrap js-fullheight" data-stellar-background-ratio="0.5"
    style="background-image: url({% static 'images/backgroundimage.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
        data-scrollax-parent="true">
        <div class="col-md-12 ftco-animate">
          <h1>Edit Blog</h1>
        </div>
      </div>
    </div>

  </div>


  <div class="container-fluid bg-darkblack d-flex justify-content-center">
    <div class="text mt-4">
      <form method="POST" class="mt-5" action="{% url 'update_post' slug %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="img-fluid">
          {{form.media}}
        </div>
        <div class="container text-center">
          <button class="links mt-1 mb-4 " type="submit">Update</button>
        </div>
      </form>
    </div>
  </div>


  {% include "footer.html" %}
</body>

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">




<head>
    <title>Home</title>
    <link rel="icon" href="{% static 'images/logo.ico'%}" type="image/x-icon">
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" />
    <meta name="_token" content="{{csrf_token}}">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
    <link href="{% static 'css/aos.css' %}" rel="stylesheet" />
    <link href="{% static 'css/ionicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet" />
    <link href="{% static 'css/icomoon.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/loader.css' %}">

</head>

<body>

    <div id="loading">
        <img id="loading-image" src="{% static 'images/ajax-loader.gif' %}" alt="Loading..." />
    </div>

    {% include "navbar.html" %}
    {% include "modal.html" %}

    <div class="hero-wrap js-fullheight" data-stellar-background-ratio="0.5"
        style="background-image: url({% static 'images/backgroundimage.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
                data-scrollax-parent="true">
                <div class="col-md-12 ftco-animate">
                    <h2 class="subheading">Hello! Welcome to</h2>
                    <h1 class="mb-4 mb-md-0">Growth blog</h1>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="text">
                                <p>We will show you the top class blogs that can have a deep impact on your living.
                                    Choose from our wide category of blogs and have fun reading new stuffs.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    
    <section>
        <div class="container-fluid" style="height: 60px;background: #0a0303;color: red">

            {% if not user.is_authenticated %}
            <marquee class="pt-3">
                Login to Add Posts !
            </marquee>
            {% else %}
            <marquee class="pt-3">
                Stay tuned for new topics !
            </marquee>
            {% endif %}
        </div>
    </section>

    <!-- start of the posts part -->
    <section class="ftco-section bg-lightblack">
        <div class="container">
            <div class="row">
                <div class="col-md-4 mt-5 mb-1">
                    <div class="cat container mt-5 text-center">

                        <div class="container">
                            <ul class="list-group list-group-flush mt-5">
                                <li class="list-group-item bg-darkblack">Select your Category</li>
                                {% for category in all_categories %}
                                <li class="list-group-item bg-darkblack"><a
                                        href="{% url 'category' category.category %}">{{category.category}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                </div>


                <div class="col-md-8">

                    {% for post in all_posts %}

                    <div class="row bg-darkblack mt-5">
                        <div class="col-md-6 mt-5" style="padding-left: 0px;">
                            <a href="{% url 'post_detail' post.slug %}"><img class="img-fluid mt-5"
                                    src={{post.thumb_url}}
                                    style="width:100%; max-height:100%; min-height:240px; margin:10px; position :relative;" /></a>
                        </div>


                        <div class="col-md-6">
                            <div class="container text-center">
                                <h3 class="text-white mb-3 mt-2">
                                    <a href="{% url 'post_detail' post.slug %}"
                                        style="text-decoration: none;">{{post.heading|slice:":40"}}...
                                    </a>
                                </h3>
                            </div>

                            <p class="text-break">
                                {{post.body|safe|slice:":200"}}
                            </p>
                        </div>

                    </div>
                    <br />
                    {% endfor %}
                </div>

            </div>
        </div>
    </section>


    {% comment %} <section class="ftco-section bg-darkblack">

        <div class="container">
            <div class="container text-center">
                <h3 class="text-uppercase text-white">
                    This are the popular topics
                </h3>


                <div class="row mt-5">
                    <div class="col-md-6">

                        <div class="bg-lightblack mt-3">
                            <div class="container text-center">
                                <h4 class="text-white">tech</h4>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">

                        <div class="bg-lightblack mt-3">
                            <div class="container text-center">
                                <h4 class="text-white">tech</h4>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">

                        <div class="bg-lightblack mt-3">
                            <div class="container text-center">
                                <h4 class="text-white">tech</h4>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">

                        <div class="bg-lightblack mt-3">
                            <div class="container text-center">
                                <h4 class="text-white">tech</h4>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </section>

    <section class="ftco-section bg-lightblack">

        <div class="container">
            <div class="row">

                <div class="col-md-6">
                    <div class="container text-center">
                        <h2 class="text-white">This are the popular Posts</h2>
                    </div>
                </div>

                <div class="col-md-6">

                    <div class="row">
                        <div class="col-md-6">

                            <div class="bg-darkblack">
                                <div class="container text-center">
                                    <h4 class="text-white">tech</h4>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">

                            <div class="bg-darkblack">
                                <div class="container text-center">
                                    <h4 class="text-white">tech</h4>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">

                            <div class="bg-darkblack">
                                <div class="container text-center">
                                    <h4 class="text-white">tech</h4>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">

                            <div class="bg-darkblack">
                                <div class="container text-center">
                                    <h4 class="text-white">tech</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>

    </section> {% endcomment %}



    <script>
        $(window).on('load', function () {
            $('#loading').hide();
        });
    </script>


    {% include "footer.html" %}

</body>

</html>

templates/navbar.html
<nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Growth<i>Hackers</i></a>
        <button aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#ftco-nav" data-toggle="collapse" type="button">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                <li class="nav-item dropdown">
                    <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle"
                        data-toggle="dropdown" href="#" role="button">Categories</a>
                    <div class="dropdown-menu bg-dark">
                        {% for category in all_categories %}
                        <a class="dropdown-item eventnav bg-dark text-white" href="{% url 'category' category.category %}">{{category.category}}</a>
                        {% endfor %}
                    </div>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'add_blog' %}">Add blog</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'show_post' %}">Show Post</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About Us</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" data-target="#exampleModal" data-toggle="modal" href="#!">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{{post.heading}}</title>
  <link rel="icon" href="{% static 'images/logo.ico'%}" type="image/x-icon">
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" />
  <meta name="_token" content="{{csrf_token}}">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link href="{% static 'css/open-iconic-bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
  <link href="{% static 'css/aos.css' %}" rel="stylesheet" />
  <link href="{% static 'css/ionicons.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/flaticon.css' %}" rel="stylesheet" />
  <link href="{% static 'css/icomoon.css' %}" rel="stylesheet" />
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/loader.css' %}">

  <style>
    img {
      object-fit: contain !important;
      position: relative !important;
      max-width: 100% !important;
      max-height: 100% !important;
    }
  </style>

</head>

<body>
{% include "navbar.html" %}
{% include "modal.html" %}






  <div class="hero-wrap js-fullheight" data-stellar-background-ratio="0.5"
    style="background-image: url({% static 'images/backgroundimage.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
        data-scrollax-parent="true">
        <div class="col-md-12 ftco-animate">
          <h1>{{post.category}}</h1>
        </div>
      </div>
    </div>
  </div>


  <div class="container-fluid d-flex justify-content-center">
    <div class="text mt-4">
      <div class="container">
        <h2>{{post.heading}}
        </h2>
        <div class="row mt-4">
          <div class="col mb-4"> Author: <strong>{{post.user}}</strong></div>
          <div class="col mb-4">Updated On: <strong>{{post.creation_date}}</strong></div>
        </div>
        {{post.body|safe}}
      </div>
    </div>
  </div>


{% if request.user == post.user %}
  <div class="container-fluid d-flex bg-lightblack">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-6">
          <a href="{% url 'edit_post' post.slug %}" class="links mt-4 mb-4">Update Post</a>
        </div>
        <div class="col-lg-6">
          <a href="{% url 'delete_post' post.slug %}" class="links mt-4 mb-4">Delete Post</a>
        </div>
      </div>
    </div>
  </div>
{% endif %}



  {% include "footer.html" %}
</body>

</html>